# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Facun/Desktop/TD1_TPS_Locales/Exercise_Guide_Chapter_15/guia_15/guia_15.srcs/sources_1/ip/pcMem/pcMem.xci
# IP: The module: 'pcMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Facun/Desktop/TD1_TPS_Locales/Exercise_Guide_Chapter_15/guia_15/guia_15.gen/sources_1/ip/pcMem/pcMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcMem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Facun/Desktop/TD1_TPS_Locales/Exercise_Guide_Chapter_15/guia_15/guia_15.srcs/sources_1/ip/pcMem/pcMem.xci
# IP: The module: 'pcMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Facun/Desktop/TD1_TPS_Locales/Exercise_Guide_Chapter_15/guia_15/guia_15.gen/sources_1/ip/pcMem/pcMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
