/*
 * Ui_Historial.h
 *
 *  Created on: 20 Nov. 2024
 *      Author: Ezequiel Lagatche
 *		ESP --> Descripción: Configuración de la interfaz gráfica para la ventana de historial médico (generada automáticamente por Qt).
 *      ENG --> Description: UI configuration for medical history window (auto-generated by Qt).
 *
 */

/* ESP
 * @brief Este archivo define la clase Ui_Historial que configura todos los elementos gráficos de la ventana de historial médico.
 *        Incluye botones de gestión de datos, área de texto para visualización, y disposición espacial de los componentes.
 *
 *      **Clase Ui_Historial**
 *
 *      **Elementos de Interfaz**
 *
 *      centralwidget:      Widget contenedor principal de la ventana.
 *      gridLayout:         Layout de cuadrícula para organizar los elementos.
 *      horizontalSpacer:   Espaciador horizontal para distribución de botones.
 *      botonMenu:          Botón "Atrás" para volver al menú principal.
 *      botonGuardar:       Botón "Guardar" para persistir cambios en el historial.
 *      botonBorrar:        Botón "Borrar" para eliminar registros seleccionados.
 *      botonSalir:         Botón "Salir" para cerrar la ventana.
 *      botonEditar:        Botón "Editar" para modificar registros existentes.
 *      textEdit:           Área de texto para visualizar el historial médico.
 *      menubar:            Barra de menú superior (vacía por defecto).
 *      statusbar:          Barra de estado inferior (vacía por defecto).
 *
 *      **Métodos**
 *
 *      setupUi(QMainWindow *Historial):
 *                          Inicializa y configura todos los componentes gráficos.
 *                          - Define geometría de la ventana (639x345 px)
 *                          - Establece tipografía "Manjari" como predeterminada
 *                          - Configura tamaños mínimos de botones (100x50 px)
 *                          - Organiza elementos en el gridLayout
 *
 *      retranslateUi(QMainWindow *Historial):
 *                          Asigna textos traducibles a los elementos de la interfaz.
 *                          - Títulos de ventana y botones
 *
 *      **Namespace Ui**
 *
 *      class Historial: public Ui_Historial {}:
 *                          Herencia para exponer la interfaz como clase pública.
 *
 * @param Ninguno
 */

/* ENG
 * @brief This file defines the Ui_Historial class configuring all graphical elements for the medical history window.
 *        Includes data management buttons, text display area, and spatial arrangement of components.
 *
 *      **Class Ui_Historial**
 *
 *      **UI Elements**
 *
 *      centralwidget:      Main container widget of the window.
 *      gridLayout:         Grid layout for element organization.
 *      horizontalSpacer:   Horizontal spacer for button distribution.
 *      botonMenu:          "Back" button to return to main menu.
 *      botonGuardar:       "Save" button to persist history changes.
 *      botonBorrar:        "Delete" button to remove selected records.
 *      botonSalir:         "Exit" button to close the window.
 *      botonEditar:        "Edit" button to modify existing records.
 *      textEdit:           Text area to display medical history.
 *      menubar:            Top menu bar (empty by default).
 *      statusbar:          Bottom status bar (empty by default).
 *
 *      **Methods**
 *
 *      setupUi(QMainWindow *Historial):
 *                          Initializes and configures all graphical components.
 *                          - Defines window geometry (639x345 px)
 *                          - Sets "Manjari" as default font
 *                          - Configures minimum button sizes (100x50 px)
 *                          - Arranges elements in gridLayout
 *
 *      retranslateUi(QMainWindow *Historial):
 *                          Assigns translatable texts to UI elements.
 *                          - Window title and button labels
 *
 *      **Namespace Ui**
 *
 *      class Historial: public Ui_Historial {}:
 *                          Inheritance to expose UI as public class.
 *
 * @param None
 */

#ifndef UI_HISTORIAL_H
#define UI_HISTORIAL_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Historial
{
public:
    QWidget *centralwidget;
    QGridLayout *gridLayout;
    QSpacerItem *horizontalSpacer;
    QPushButton *botonMenu;
    QPushButton *botonGuardar;
    QPushButton *botonBorrar;
    QPushButton *botonSalir;
    QPushButton *botonEditar;
    QTextEdit *textEdit;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *Historial)
    {
        if (Historial->objectName().isEmpty())
            Historial->setObjectName(QString::fromUtf8("Historial"));
        Historial->resize(639, 345);
        QFont font;
        font.setFamilies({QString::fromUtf8("Manjari")});
        Historial->setFont(font);
        centralwidget = new QWidget(Historial);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        gridLayout = new QGridLayout(centralwidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        gridLayout->addItem(horizontalSpacer, 2, 3, 1, 1);

        botonMenu = new QPushButton(centralwidget);
        botonMenu->setObjectName(QString::fromUtf8("botonMenu"));
        botonMenu->setMinimumSize(QSize(100, 50));

        gridLayout->addWidget(botonMenu, 2, 4, 1, 1);

        botonGuardar = new QPushButton(centralwidget);
        botonGuardar->setObjectName(QString::fromUtf8("botonGuardar"));
        botonGuardar->setMinimumSize(QSize(100, 50));

        gridLayout->addWidget(botonGuardar, 2, 1, 1, 1);

        botonBorrar = new QPushButton(centralwidget);
        botonBorrar->setObjectName(QString::fromUtf8("botonBorrar"));
        botonBorrar->setMinimumSize(QSize(100, 50));

        gridLayout->addWidget(botonBorrar, 2, 2, 1, 1);

        botonSalir = new QPushButton(centralwidget);
        botonSalir->setObjectName(QString::fromUtf8("botonSalir"));
        botonSalir->setMinimumSize(QSize(100, 50));

        gridLayout->addWidget(botonSalir, 2, 5, 1, 1);

        botonEditar = new QPushButton(centralwidget);
        botonEditar->setObjectName(QString::fromUtf8("botonEditar"));
        botonEditar->setMinimumSize(QSize(100, 50));

        gridLayout->addWidget(botonEditar, 2, 0, 1, 1);

        textEdit = new QTextEdit(centralwidget);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setFrameShape(QFrame::StyledPanel);

        gridLayout->addWidget(textEdit, 0, 0, 1, 6);

        Historial->setCentralWidget(centralwidget);
        menubar = new QMenuBar(Historial);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 639, 22));
        Historial->setMenuBar(menubar);
        statusbar = new QStatusBar(Historial);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        Historial->setStatusBar(statusbar);

        retranslateUi(Historial);

        QMetaObject::connectSlotsByName(Historial);
    } // setupUi

    void retranslateUi(QMainWindow *Historial)
    {
        Historial->setWindowTitle(QCoreApplication::translate("Historial", "MainWindow", nullptr));
        botonMenu->setText(QCoreApplication::translate("Historial", "Atras", nullptr));
        botonGuardar->setText(QCoreApplication::translate("Historial", "Guardar", nullptr));
        botonBorrar->setText(QCoreApplication::translate("Historial", "Borrar", nullptr));
        botonSalir->setText(QCoreApplication::translate("Historial", "Salir", nullptr));
        botonEditar->setText(QCoreApplication::translate("Historial", "Editar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Historial: public Ui_Historial {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HISTORIAL_H
