/*
 * Ui_Pacientes.h
 *
 *  Created on: 20 Nov. 2024
 *      Author: Ezequiel Lagatche
 *		ESP --> Descripción: Configuración de la interfaz gráfica para el diálogo de captura de datos de pacientes (generada automáticamente por Qt).
 *      ENG --> Description: UI configuration for patient data input dialog (auto-generated by Qt).
 *
 */

/* ESP
 * @brief Este archivo define la clase Ui_Pacientes que configura los elementos gráficos para el ingreso de información médica de pacientes.
 *        Incluye campos para datos personales, selección de género y botones de confirmación/cancelación.
 *
 *      **Clase Ui_Pacientes**
 *
 *      **Elementos de Interfaz**
 *
 *      gridLayout:         Layout principal de cuadrícula para organización vertical.
 *      verticalSpacer:     Espaciador vertical para distribución equilibrada de elementos.
 *      labelNombre:        Etiqueta "Nombre" para campo de nombre del paciente.
 *      labelApellido:      Etiqueta "Apellido" para campo de apellido.
 *      labelDNI:           Etiqueta "DNI" para campo de documento nacional de identidad.
 *      labelSexo:          Etiqueta "Sexo" para grupo de selección de género.
 *      buttonBox:          Botonera estándar Ok/Cancel para confirmar o descartar datos.
 *      groupBox:           Contenedor para los botones de radio de selección de género.
 *      radioButtonH:       Botón radio "Hombre" para género masculino.
 *      radioButtonM:       Botón radio "Mujer" para género femenino.
 *      lineEditDNI:        Campo de texto numérico para ingreso de DNI.
 *      lineEditApellido:   Campo de texto para apellido del paciente.
 *      lineEditNombre:     Campo de texto para nombre del paciente.
 *
 *      **Métodos**
 *
 *      setupUi(QDialog *Pacientes):
 *                          Configuración inicial de la interfaz:
 *                          - Tamaño de diálogo: 346x220 px
 *                          - Tipografía base: Manjari
 *                          - Organización en gridLayout con 7 filas
 *                          - Conexión automática de señales Ok/Cancel
 *
 *      retranslateUi(QDialog *Pacientes):
 *                          Asignación de textos traducibles:
 *                          - Etiquetas de campos
 *                          - Textos de botones radio
 *                          - Título de ventana
 *
 *      **Namespace Ui**
 *
 *      class Pacientes: public Ui_Pacientes {}:
 *                          Herencia para exponer la interfaz como clase pública.
 *
 * @param Ninguno
 */

/* ENG
 * @brief This file defines the Ui_Pacientes class configuring graphical elements for patient medical data input.
 *        Includes personal data fields, gender selection, and confirmation/cancelation buttons.
 *
 *      **Class Ui_Pacientes**
 *
 *      **UI Elements**
 *
 *      gridLayout:         Main grid layout for vertical organization.
 *      verticalSpacer:     Vertical spacer for balanced element distribution.
 *      labelNombre:        "Name" label for patient's first name field.
 *      labelApellido:      "Last Name" label for surname field.
 *      labelDNI:           "ID Number" label for national identification field.
 *      labelSexo:          "Gender" label for selection group.
 *      buttonBox:          Standard Ok/Cancel button box for data confirmation.
 *      groupBox:           Container for gender radio buttons.
 *      radioButtonH:       "Male" radio button for masculine gender.
 *      radioButtonM:       "Female" radio button for feminine gender.
 *      lineEditDNI:        Numeric text field for ID input.
 *      lineEditApellido:   Text field for patient's last name.
 *      lineEditNombre:     Text field for patient's first name.
 *
 *      **Methods**
 *
 *      setupUi(QDialog *Pacientes):
 *                          Initial UI configuration:
 *                          - Dialog size: 346x220 px
 *                          - Base font: Manjari
 *                          - Grid layout organization with 7 rows
 *                          - Automatic Ok/Cancel signals connection
 *
 *      retranslateUi(QDialog *Pacientes):
 *                          Translatable text assignment:
 *                          - Field labels
 *                          - Radio button texts
 *                          - Window title
 *
 *      **Namespace Ui**
 *
 *      class Pacientes: public Ui_Pacientes {}:
 *                          Inheritance to expose UI as public class.
 *
 * @param None
 */

#ifndef UI_PACIENTES_H
#define UI_PACIENTES_H

#include <QtCore/QVariant>
#include <QtWidgets/QAbstractButton>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpacerItem>

QT_BEGIN_NAMESPACE

class Ui_Pacientes
{
public:
    QGridLayout *gridLayout;
    QSpacerItem *verticalSpacer;
    QLabel *labelNombre;
    QLabel *labelApellido;
    QLabel *labelDNI;
    QLabel *labelSexo;
    QDialogButtonBox *buttonBox;
    QGroupBox *groupBox;
    QHBoxLayout *horizontalLayout;
    QRadioButton *radioButtonH;
    QRadioButton *radioButtonM;
    QLineEdit *lineEditDNI;
    QLineEdit *lineEditApellido;
    QLineEdit *lineEditNombre;

    void setupUi(QDialog *Pacientes)
    {
        if (Pacientes->objectName().isEmpty())
            Pacientes->setObjectName(QString::fromUtf8("Pacientes"));
        Pacientes->resize(346, 220);
        QFont font;
        font.setFamilies({QString::fromUtf8("Manjari")});
        Pacientes->setFont(font);
        gridLayout = new QGridLayout(Pacientes);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        verticalSpacer = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        gridLayout->addItem(verticalSpacer, 4, 2, 1, 1);

        labelNombre = new QLabel(Pacientes);
        labelNombre->setObjectName(QString::fromUtf8("labelNombre"));

        gridLayout->addWidget(labelNombre, 0, 0, 1, 1);

        labelApellido = new QLabel(Pacientes);
        labelApellido->setObjectName(QString::fromUtf8("labelApellido"));

        gridLayout->addWidget(labelApellido, 1, 0, 1, 1);

        labelDNI = new QLabel(Pacientes);
        labelDNI->setObjectName(QString::fromUtf8("labelDNI"));

        gridLayout->addWidget(labelDNI, 2, 0, 1, 1);

        labelSexo = new QLabel(Pacientes);
        labelSexo->setObjectName(QString::fromUtf8("labelSexo"));

        gridLayout->addWidget(labelSexo, 3, 0, 1, 1);

        buttonBox = new QDialogButtonBox(Pacientes);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);

        gridLayout->addWidget(buttonBox, 6, 1, 1, 3);

        groupBox = new QGroupBox(Pacientes);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        horizontalLayout = new QHBoxLayout(groupBox);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        radioButtonH = new QRadioButton(groupBox);
        radioButtonH->setObjectName(QString::fromUtf8("radioButtonH"));

        horizontalLayout->addWidget(radioButtonH);

        radioButtonM = new QRadioButton(groupBox);
        radioButtonM->setObjectName(QString::fromUtf8("radioButtonM"));

        horizontalLayout->addWidget(radioButtonM);


        gridLayout->addWidget(groupBox, 3, 1, 1, 3);

        lineEditDNI = new QLineEdit(Pacientes);
        lineEditDNI->setObjectName(QString::fromUtf8("lineEditDNI"));

        gridLayout->addWidget(lineEditDNI, 2, 1, 1, 3);

        lineEditApellido = new QLineEdit(Pacientes);
        lineEditApellido->setObjectName(QString::fromUtf8("lineEditApellido"));

        gridLayout->addWidget(lineEditApellido, 1, 1, 1, 3);

        lineEditNombre = new QLineEdit(Pacientes);
        lineEditNombre->setObjectName(QString::fromUtf8("lineEditNombre"));

        gridLayout->addWidget(lineEditNombre, 0, 1, 1, 3);


        retranslateUi(Pacientes);
        QObject::connect(buttonBox, &QDialogButtonBox::accepted, Pacientes, qOverload<>(&QDialog::accept));
        QObject::connect(buttonBox, &QDialogButtonBox::rejected, Pacientes, qOverload<>(&QDialog::reject));

        QMetaObject::connectSlotsByName(Pacientes);
    } // setupUi

    void retranslateUi(QDialog *Pacientes)
    {
        Pacientes->setWindowTitle(QCoreApplication::translate("Pacientes", "Dialog", nullptr));
        labelNombre->setText(QCoreApplication::translate("Pacientes", "Nombre", nullptr));
        labelApellido->setText(QCoreApplication::translate("Pacientes", "Apellido", nullptr));
        labelDNI->setText(QCoreApplication::translate("Pacientes", "DNI", nullptr));
        labelSexo->setText(QCoreApplication::translate("Pacientes", "Sexo", nullptr));
        groupBox->setTitle(QString());
        radioButtonH->setText(QCoreApplication::translate("Pacientes", "Hombre", nullptr));
        radioButtonM->setText(QCoreApplication::translate("Pacientes", "Mujer", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Pacientes: public Ui_Pacientes {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PACIENTES_H
