/*
 * Ui_VentanaConexion.h
 *
 *  Created on: 20 Nov. 2024
 *      Author: Ezequiel Lagatche
 *		ESP --> Descripción: Configuración de la interfaz gráfica para la ventana de selección de puerto TCP (generada automáticamente por Qt).
 *      ENG --> Description: UI configuration for TCP port selection window (auto-generated by Qt).
 *
 */

/* ESP
 * @brief Este archivo define la clase Ui_VentanaConexion que gestiona la interfaz para establecer conexiones TCP.
 *        Incluye campo de entrada para el puerto y botón de acción para iniciar la conexión.

 *      **Clase Ui_VentanaConexion**

 *      **Elementos de Interfaz**

 *      centralwidget:      Widget contenedor principal de la ventana.
 *      gridLayout:         Layout de cuadrícula principal para organización general.
 *      groupBox:           Grupo contenedor para elementos de conexión.
 *      gridLayout_2:       Layout interno del groupBox para alineación vertical.
 *      label:              Etiqueta "Puerto" para identificar el campo de entrada.
 *      lineEditPort:       Campo de texto para ingreso numérico del puerto TCP.
 *      pushButtonConexion: Botón "Conectar" para iniciar la conexión al puerto especificado.
 *      statusbar:          Barra de estado inferior (vacía por defecto).

 *      **Métodos**

 *      setupUi(QMainWindow *VentanaConexion):
 *                          Configuración inicial de la interfaz:
 *                          - Tamaño de ventana: 337x145 px
 *                          - Tipografía base: Manjari
 *                          - Mínima altura del groupBox: 105 px
 *                          - Organización jerárquica de layouts

 *      retranslateUi(QMainWindow *VentanaConexion):
 *                          Asignación de textos traducibles:
 *                          - Título de ventana: "MainWindow"
 *                          - Título del groupBox: "Seleccion de Puerto"
 *                          - Textos de etiquetas y botón

 *      **Namespace Ui**

 *      class VentanaConexion: public Ui_VentanaConexion {}:
 *                          Herencia para exponer la interfaz como clase pública.

 * @param Ninguno
 */

/* ENG
 * @brief This file defines the Ui_VentanaConexion class managing the interface for TCP connections setup.
 *        Includes port input field and action button to establish connection.

 *      **Class Ui_VentanaConexion**

 *      **UI Elements**

 *      centralwidget:      Main container widget of the window.
 *      gridLayout:         Main grid layout for general organization.
 *      groupBox:           Container group for connection elements.
 *      gridLayout_2:       Internal groupBox layout for vertical alignment.
 *      label:              "Port" label identifying the input field.
 *      lineEditPort:       Text field for numeric TCP port input.
 *      pushButtonConexion: "Connect" button to initiate port connection.
 *      statusbar:          Bottom status bar (empty by default).

 *      **Methods**

 *      setupUi(QMainWindow *VentanaConexion):
 *                          Initial UI configuration:
 *                          - Window size: 337x145 px
 *                          - Base font: Manjari
 *                          - groupBox minimum height: 105 px
 *                          - Hierarchical layout organization

 *      retranslateUi(QMainWindow *VentanaConexion):
 *                          Translatable text assignment:
 *                          - Window title: "MainWindow"
 *                          - groupBox title: "Seleccion de Puerto"
 *                          - Label and button texts

 *      **Namespace Ui**

 *      class VentanaConexion: public Ui_VentanaConexion {}:
 *                          Inheritance to expose UI as public class.

 * @param None
 */

#ifndef UI_VENTANACONEXION_H
#define UI_VENTANACONEXION_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VentanaConexion
{
public:
    QWidget *centralwidget;
    QGridLayout *gridLayout;
    QGroupBox *groupBox;
    QGridLayout *gridLayout_2;
    QLabel *label;
    QLineEdit *lineEditPort;
    QPushButton *pushButtonConexion;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *VentanaConexion)
    {
        if (VentanaConexion->objectName().isEmpty())
            VentanaConexion->setObjectName(QString::fromUtf8("VentanaConexion"));
        VentanaConexion->resize(337, 145);
        QFont font;
        font.setFamilies({QString::fromUtf8("Manjari")});
        VentanaConexion->setFont(font);
        centralwidget = new QWidget(VentanaConexion);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        gridLayout = new QGridLayout(centralwidget);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setMinimumSize(QSize(0, 105));
        gridLayout_2 = new QGridLayout(groupBox);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));

        gridLayout_2->addWidget(label, 0, 0, 1, 1);

        lineEditPort = new QLineEdit(groupBox);
        lineEditPort->setObjectName(QString::fromUtf8("lineEditPort"));

        gridLayout_2->addWidget(lineEditPort, 0, 1, 1, 2);

        pushButtonConexion = new QPushButton(groupBox);
        pushButtonConexion->setObjectName(QString::fromUtf8("pushButtonConexion"));

        gridLayout_2->addWidget(pushButtonConexion, 1, 1, 1, 1);


        gridLayout->addWidget(groupBox, 0, 1, 1, 1);

        VentanaConexion->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(VentanaConexion);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        VentanaConexion->setStatusBar(statusbar);

        retranslateUi(VentanaConexion);

        QMetaObject::connectSlotsByName(VentanaConexion);
    } // setupUi

    void retranslateUi(QMainWindow *VentanaConexion)
    {
        VentanaConexion->setWindowTitle(QCoreApplication::translate("VentanaConexion", "MainWindow", nullptr));
        groupBox->setTitle(QCoreApplication::translate("VentanaConexion", "Seleccion de Puerto", nullptr));
        label->setText(QCoreApplication::translate("VentanaConexion", "Puerto", nullptr));
        pushButtonConexion->setText(QCoreApplication::translate("VentanaConexion", "Conectar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class VentanaConexion: public Ui_VentanaConexion {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VENTANACONEXION_H
